name: agroo_test
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # stacked
  stacked:
  stacked_hooks: ^0.2.1
  stacked_services:
  logger: ^1.0.0

  # utils
  flutter_screenutil: ^5.0.0+2
  shimmer: ^2.0.0

  # network
  dio: ^4.0.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  stacked_generator:
  build_runner: ^2.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/social_icons/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

